title: MobilePay PoS
base_url: https://mobilepaydev.github.io/MobilePay-PoS-Titanium/
description: MobilePay PoS API documentation.
show_downloads: false
theme: jekyll-theme-minimal
repository: MobilePayDev/MobilePay-PoS-Titanium
